/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIdentityRegistry,
  IIdentityRegistryInterface,
} from "../../interfaces/IIdentityRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "encryptionKeyOf",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "profileOf",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "encryptionPubKey",
            type: "bytes32",
          },
          {
            internalType: "string",
            name: "profileCid",
            type: "string",
          },
          {
            internalType: "bool",
            name: "personhood",
            type: "bool",
          },
          {
            internalType: "uint64",
            name: "registeredAt",
            type: "uint64",
          },
        ],
        internalType: "struct IIdentityRegistry.Profile",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIdentityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IIdentityRegistryInterface {
    return new Interface(_abi) as IIdentityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIdentityRegistry {
    return new Contract(address, _abi, runner) as unknown as IIdentityRegistry;
  }
}
