/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIndividuality,
  IIndividualityInterface,
} from "../../interfaces/IIndividuality";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "context",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "dimOf",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "context",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "isUnique",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIndividuality__factory {
  static readonly abi = _abi;
  static createInterface(): IIndividualityInterface {
    return new Interface(_abi) as IIndividualityInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIndividuality {
    return new Contract(address, _abi, runner) as unknown as IIndividuality;
  }
}
