/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IIdentityRegistry__factory } from "./IIdentityRegistry__factory";
export { IIndividuality__factory } from "./IIndividuality__factory";
