/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IndividualityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dimOf"
      | "isUnique"
      | "nullifierUsed"
      | "owner"
      | "peopleChainBridge"
      | "peopleRoot"
      | "registerAlias"
      | "revokeAlias"
      | "setBridge"
      | "setPeopleRoot"
      | "setVerifier"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AliasRegistered"
      | "AliasRevoked"
      | "PeopleRootUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dimOf",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUnique",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nullifierUsed",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "peopleChainBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "peopleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAlias",
    values: [BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAlias",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPeopleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dimOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isUnique", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "peopleChainBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "peopleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAlias",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAlias",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPeopleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace AliasRegisteredEvent {
  export type InputTuple = [
    context: BytesLike,
    aliasAccount: AddressLike,
    nullifier: BytesLike,
    dim: BigNumberish
  ];
  export type OutputTuple = [
    context: string,
    aliasAccount: string,
    nullifier: string,
    dim: bigint
  ];
  export interface OutputObject {
    context: string;
    aliasAccount: string;
    nullifier: string;
    dim: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AliasRevokedEvent {
  export type InputTuple = [context: BytesLike, aliasAccount: AddressLike];
  export type OutputTuple = [context: string, aliasAccount: string];
  export interface OutputObject {
    context: string;
    aliasAccount: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeopleRootUpdatedEvent {
  export type InputTuple = [root: BytesLike];
  export type OutputTuple = [root: string];
  export interface OutputObject {
    root: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Individuality extends BaseContract {
  connect(runner?: ContractRunner | null): Individuality;
  waitForDeployment(): Promise<this>;

  interface: IndividualityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dimOf: TypedContractMethod<
    [context: BytesLike, account: AddressLike],
    [bigint],
    "view"
  >;

  isUnique: TypedContractMethod<
    [context: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nullifierUsed: TypedContractMethod<
    [arg0: BytesLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  peopleChainBridge: TypedContractMethod<[], [string], "view">;

  peopleRoot: TypedContractMethod<[], [string], "view">;

  registerAlias: TypedContractMethod<
    [
      context: BytesLike,
      nullifier: BytesLike,
      dim: BigNumberish,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  revokeAlias: TypedContractMethod<[context: BytesLike], [void], "nonpayable">;

  setBridge: TypedContractMethod<[bridge: AddressLike], [void], "nonpayable">;

  setPeopleRoot: TypedContractMethod<[root: BytesLike], [void], "nonpayable">;

  setVerifier: TypedContractMethod<
    [ringVrfVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dimOf"
  ): TypedContractMethod<
    [context: BytesLike, account: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isUnique"
  ): TypedContractMethod<
    [context: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nullifierUsed"
  ): TypedContractMethod<[arg0: BytesLike, arg1: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "peopleChainBridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "peopleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAlias"
  ): TypedContractMethod<
    [
      context: BytesLike,
      nullifier: BytesLike,
      dim: BigNumberish,
      proof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAlias"
  ): TypedContractMethod<[context: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBridge"
  ): TypedContractMethod<[bridge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPeopleRoot"
  ): TypedContractMethod<[root: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[ringVrfVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AliasRegistered"
  ): TypedContractEvent<
    AliasRegisteredEvent.InputTuple,
    AliasRegisteredEvent.OutputTuple,
    AliasRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AliasRevoked"
  ): TypedContractEvent<
    AliasRevokedEvent.InputTuple,
    AliasRevokedEvent.OutputTuple,
    AliasRevokedEvent.OutputObject
  >;
  getEvent(
    key: "PeopleRootUpdated"
  ): TypedContractEvent<
    PeopleRootUpdatedEvent.InputTuple,
    PeopleRootUpdatedEvent.OutputTuple,
    PeopleRootUpdatedEvent.OutputObject
  >;

  filters: {
    "AliasRegistered(bytes32,address,bytes32,uint8)": TypedContractEvent<
      AliasRegisteredEvent.InputTuple,
      AliasRegisteredEvent.OutputTuple,
      AliasRegisteredEvent.OutputObject
    >;
    AliasRegistered: TypedContractEvent<
      AliasRegisteredEvent.InputTuple,
      AliasRegisteredEvent.OutputTuple,
      AliasRegisteredEvent.OutputObject
    >;

    "AliasRevoked(bytes32,address)": TypedContractEvent<
      AliasRevokedEvent.InputTuple,
      AliasRevokedEvent.OutputTuple,
      AliasRevokedEvent.OutputObject
    >;
    AliasRevoked: TypedContractEvent<
      AliasRevokedEvent.InputTuple,
      AliasRevokedEvent.OutputTuple,
      AliasRevokedEvent.OutputObject
    >;

    "PeopleRootUpdated(bytes32)": TypedContractEvent<
      PeopleRootUpdatedEvent.InputTuple,
      PeopleRootUpdatedEvent.OutputTuple,
      PeopleRootUpdatedEvent.OutputObject
    >;
    PeopleRootUpdated: TypedContractEvent<
      PeopleRootUpdatedEvent.InputTuple,
      PeopleRootUpdatedEvent.OutputTuple,
      PeopleRootUpdatedEvent.OutputObject
    >;
  };
}
