/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRingVrfVerifier,
  IRingVrfVerifierInterface,
} from "../../Individuality.sol/IRingVrfVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "peopleRoot",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "context",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "aliasAccount",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "nullifier",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRingVrfVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IRingVrfVerifierInterface {
    return new Interface(_abi) as IRingVrfVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRingVrfVerifier {
    return new Contract(address, _abi, runner) as unknown as IRingVrfVerifier;
  }
}
