/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockRingVrfVerifier,
  MockRingVrfVerifierInterface,
} from "../../Individuality.sol/MockRingVrfVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101448061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806388553db114610030575b600080fd5b61004a61003e36600461005e565b60019695505050505050565b604051901515815260200160405180910390f35b60008060008060008060a0878903121561007757600080fd5b863595506020870135945060408701356001600160a01b038116811461009c57600080fd5b935060608701359250608087013567ffffffffffffffff8111156100bf57600080fd5b8701601f810189136100d057600080fd5b803567ffffffffffffffff8111156100e757600080fd5b8960208284010111156100f957600080fd5b6020820193508092505050929550929550929556fea2646970667358221220dfbc49ab32742e8456fe3f8466e4852cd35907d398d22b196d055b5220c2926e64736f6c634300081a0033";

type MockRingVrfVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRingVrfVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRingVrfVerifier__factory extends ContractFactory {
  constructor(...args: MockRingVrfVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockRingVrfVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockRingVrfVerifier__factory {
    return super.connect(runner) as MockRingVrfVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRingVrfVerifierInterface {
    return new Interface(_abi) as MockRingVrfVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockRingVrfVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockRingVrfVerifier;
  }
}
