/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AnonymousMail {
  export type MailStruct = {
    cid: string;
    deliveredAt: BigNumberish;
    expiresAt: BigNumberish;
    read: boolean;
    burned: boolean;
  };

  export type MailStructOutput = [
    cid: string,
    deliveredAt: bigint,
    expiresAt: bigint,
    read: boolean,
    burned: boolean
  ] & {
    cid: string;
    deliveredAt: bigint;
    expiresAt: bigint;
    read: boolean;
    burned: boolean;
  };
}

export interface AnonymousMailInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burn"
      | "deliver"
      | "getInbox"
      | "identity"
      | "inboxCount"
      | "markRead"
      | "owner"
      | "relayer"
      | "setRelayer"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MailBurned"
      | "MailDelivered"
      | "MailRead"
      | "RelayerSet"
  ): EventFragment;

  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "deliver",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInbox",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "identity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inboxCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markRead",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "relayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayer",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deliver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getInbox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inboxCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markRead", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRelayer", data: BytesLike): Result;
}

export namespace MailBurnedEvent {
  export type InputTuple = [to: AddressLike, index: BigNumberish];
  export type OutputTuple = [to: string, index: bigint];
  export interface OutputObject {
    to: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MailDeliveredEvent {
  export type InputTuple = [
    to: AddressLike,
    index: BigNumberish,
    cid: string,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    to: string,
    index: bigint,
    cid: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    to: string;
    index: bigint;
    cid: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MailReadEvent {
  export type InputTuple = [to: AddressLike, index: BigNumberish];
  export type OutputTuple = [to: string, index: bigint];
  export interface OutputObject {
    to: string;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RelayerSetEvent {
  export type InputTuple = [relay: AddressLike, allowed: boolean];
  export type OutputTuple = [relay: string, allowed: boolean];
  export interface OutputObject {
    relay: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AnonymousMail extends BaseContract {
  connect(runner?: ContractRunner | null): AnonymousMail;
  waitForDeployment(): Promise<this>;

  interface: AnonymousMailInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burn: TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  deliver: TypedContractMethod<
    [to: AddressLike, cid: string, expiresAt: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getInbox: TypedContractMethod<
    [account: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [AnonymousMail.MailStructOutput[]],
    "view"
  >;

  identity: TypedContractMethod<[], [string], "view">;

  inboxCount: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  markRead: TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  relayer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setRelayer: TypedContractMethod<
    [relay: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deliver"
  ): TypedContractMethod<
    [to: AddressLike, cid: string, expiresAt: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getInbox"
  ): TypedContractMethod<
    [account: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [AnonymousMail.MailStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "inboxCount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "markRead"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setRelayer"
  ): TypedContractMethod<
    [relay: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MailBurned"
  ): TypedContractEvent<
    MailBurnedEvent.InputTuple,
    MailBurnedEvent.OutputTuple,
    MailBurnedEvent.OutputObject
  >;
  getEvent(
    key: "MailDelivered"
  ): TypedContractEvent<
    MailDeliveredEvent.InputTuple,
    MailDeliveredEvent.OutputTuple,
    MailDeliveredEvent.OutputObject
  >;
  getEvent(
    key: "MailRead"
  ): TypedContractEvent<
    MailReadEvent.InputTuple,
    MailReadEvent.OutputTuple,
    MailReadEvent.OutputObject
  >;
  getEvent(
    key: "RelayerSet"
  ): TypedContractEvent<
    RelayerSetEvent.InputTuple,
    RelayerSetEvent.OutputTuple,
    RelayerSetEvent.OutputObject
  >;

  filters: {
    "MailBurned(address,uint256)": TypedContractEvent<
      MailBurnedEvent.InputTuple,
      MailBurnedEvent.OutputTuple,
      MailBurnedEvent.OutputObject
    >;
    MailBurned: TypedContractEvent<
      MailBurnedEvent.InputTuple,
      MailBurnedEvent.OutputTuple,
      MailBurnedEvent.OutputObject
    >;

    "MailDelivered(address,uint256,string,uint64)": TypedContractEvent<
      MailDeliveredEvent.InputTuple,
      MailDeliveredEvent.OutputTuple,
      MailDeliveredEvent.OutputObject
    >;
    MailDelivered: TypedContractEvent<
      MailDeliveredEvent.InputTuple,
      MailDeliveredEvent.OutputTuple,
      MailDeliveredEvent.OutputObject
    >;

    "MailRead(address,uint256)": TypedContractEvent<
      MailReadEvent.InputTuple,
      MailReadEvent.OutputTuple,
      MailReadEvent.OutputObject
    >;
    MailRead: TypedContractEvent<
      MailReadEvent.InputTuple,
      MailReadEvent.OutputTuple,
      MailReadEvent.OutputObject
    >;

    "RelayerSet(address,bool)": TypedContractEvent<
      RelayerSetEvent.InputTuple,
      RelayerSetEvent.OutputTuple,
      RelayerSetEvent.OutputObject
    >;
    RelayerSet: TypedContractEvent<
      RelayerSetEvent.InputTuple,
      RelayerSetEvent.OutputTuple,
      RelayerSetEvent.OutputObject
    >;
  };
}
