/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AnonymousMail",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AnonymousMail__factory>;
    getContractFactory(
      name: "IdentityRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityRegistry__factory>;
    getContractFactory(
      name: "Individuality",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Individuality__factory>;
    getContractFactory(
      name: "IRingVrfVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRingVrfVerifier__factory>;
    getContractFactory(
      name: "MockRingVrfVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockRingVrfVerifier__factory>;
    getContractFactory(
      name: "IIdentityRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentityRegistry__factory>;
    getContractFactory(
      name: "IIndividuality",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIndividuality__factory>;
    getContractFactory(
      name: "Messenger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Messenger__factory>;
    getContractFactory(
      name: "Payments",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Payments__factory>;

    getContractAt(
      name: "AnonymousMail",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AnonymousMail>;
    getContractAt(
      name: "IdentityRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityRegistry>;
    getContractAt(
      name: "Individuality",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Individuality>;
    getContractAt(
      name: "IRingVrfVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRingVrfVerifier>;
    getContractAt(
      name: "MockRingVrfVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockRingVrfVerifier>;
    getContractAt(
      name: "IIdentityRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentityRegistry>;
    getContractAt(
      name: "IIndividuality",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIndividuality>;
    getContractAt(
      name: "Messenger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Messenger>;
    getContractAt(
      name: "Payments",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Payments>;

    deployContract(
      name: "AnonymousMail",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AnonymousMail>;
    deployContract(
      name: "IdentityRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistry>;
    deployContract(
      name: "Individuality",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Individuality>;
    deployContract(
      name: "IRingVrfVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRingVrfVerifier>;
    deployContract(
      name: "MockRingVrfVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockRingVrfVerifier>;
    deployContract(
      name: "IIdentityRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistry>;
    deployContract(
      name: "IIndividuality",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIndividuality>;
    deployContract(
      name: "Messenger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Messenger>;
    deployContract(
      name: "Payments",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Payments>;

    deployContract(
      name: "AnonymousMail",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AnonymousMail>;
    deployContract(
      name: "IdentityRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityRegistry>;
    deployContract(
      name: "Individuality",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Individuality>;
    deployContract(
      name: "IRingVrfVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRingVrfVerifier>;
    deployContract(
      name: "MockRingVrfVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockRingVrfVerifier>;
    deployContract(
      name: "IIdentityRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistry>;
    deployContract(
      name: "IIndividuality",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIndividuality>;
    deployContract(
      name: "Messenger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Messenger>;
    deployContract(
      name: "Payments",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Payments>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
