/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IIdentityRegistry {
  export type ProfileStruct = {
    encryptionPubKey: BytesLike;
    profileCid: string;
    personhood: boolean;
    registeredAt: BigNumberish;
  };

  export type ProfileStructOutput = [
    encryptionPubKey: string,
    profileCid: string,
    personhood: boolean,
    registeredAt: bigint
  ] & {
    encryptionPubKey: string;
    profileCid: string;
    personhood: boolean;
    registeredAt: bigint;
  };
}

export interface IdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestPersonhood"
      | "encryptionKeyOf"
      | "isRegistered"
      | "owner"
      | "personhoodAttester"
      | "profileOf"
      | "register"
      | "setAttester"
      | "updateProfile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PersonhoodAttested"
      | "ProfileUpdated"
      | "Registered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attestPersonhood",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptionKeyOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "personhoodAttester",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "profileOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttester",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "attestPersonhood",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptionKeyOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "personhoodAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profileOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAttester",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
}

export namespace PersonhoodAttestedEvent {
  export type InputTuple = [account: AddressLike, personhood: boolean];
  export type OutputTuple = [account: string, personhood: boolean];
  export interface OutputObject {
    account: string;
    personhood: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [account: AddressLike, profileCid: string];
  export type OutputTuple = [account: string, profileCid: string];
  export interface OutputObject {
    account: string;
    profileCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisteredEvent {
  export type InputTuple = [
    account: AddressLike,
    encryptionPubKey: BytesLike,
    profileCid: string
  ];
  export type OutputTuple = [
    account: string,
    encryptionPubKey: string,
    profileCid: string
  ];
  export interface OutputObject {
    account: string;
    encryptionPubKey: string;
    profileCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestPersonhood: TypedContractMethod<
    [account: AddressLike, value: boolean],
    [void],
    "nonpayable"
  >;

  encryptionKeyOf: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  isRegistered: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  personhoodAttester: TypedContractMethod<[], [string], "view">;

  profileOf: TypedContractMethod<
    [account: AddressLike],
    [IIdentityRegistry.ProfileStructOutput],
    "view"
  >;

  register: TypedContractMethod<
    [encryptionPubKey: BytesLike, profileCid: string],
    [void],
    "nonpayable"
  >;

  setAttester: TypedContractMethod<
    [attester: AddressLike],
    [void],
    "nonpayable"
  >;

  updateProfile: TypedContractMethod<
    [profileCid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestPersonhood"
  ): TypedContractMethod<
    [account: AddressLike, value: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptionKeyOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "personhoodAttester"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "profileOf"
  ): TypedContractMethod<
    [account: AddressLike],
    [IIdentityRegistry.ProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [encryptionPubKey: BytesLike, profileCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAttester"
  ): TypedContractMethod<[attester: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<[profileCid: string], [void], "nonpayable">;

  getEvent(
    key: "PersonhoodAttested"
  ): TypedContractEvent<
    PersonhoodAttestedEvent.InputTuple,
    PersonhoodAttestedEvent.OutputTuple,
    PersonhoodAttestedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;

  filters: {
    "PersonhoodAttested(address,bool)": TypedContractEvent<
      PersonhoodAttestedEvent.InputTuple,
      PersonhoodAttestedEvent.OutputTuple,
      PersonhoodAttestedEvent.OutputObject
    >;
    PersonhoodAttested: TypedContractEvent<
      PersonhoodAttestedEvent.InputTuple,
      PersonhoodAttestedEvent.OutputTuple,
      PersonhoodAttestedEvent.OutputObject
    >;

    "ProfileUpdated(address,string)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "Registered(address,bytes32,string)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
  };
}
