/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Messenger {
  export type MessageStruct = {
    from: AddressLike;
    to: AddressLike;
    channel: BytesLike;
    cid: string;
    sentAt: BigNumberish;
    expiresAt: BigNumberish;
    burned: boolean;
  };

  export type MessageStructOutput = [
    from: string,
    to: string,
    channel: string,
    cid: string,
    sentAt: bigint,
    expiresAt: bigint,
    burned: boolean
  ] & {
    from: string;
    to: string;
    channel: string;
    cid: string;
    sentAt: bigint;
    expiresAt: bigint;
    burned: boolean;
  };
}

export interface MessengerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "burn"
      | "channels"
      | "createChannel"
      | "dmId"
      | "getMessages"
      | "identity"
      | "individuality"
      | "messageCount"
      | "sendDirect"
      | "sendToChannel"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ChannelCreated" | "MessageBurned" | "MessageSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "burn",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "channels", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "createChannel",
    values: [BytesLike, boolean, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "dmId",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessages",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "identity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "individuality",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendDirect",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendToChannel",
    values: [BytesLike, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "channels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dmId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "individuality",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendDirect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendToChannel",
    data: BytesLike
  ): Result;
}

export namespace ChannelCreatedEvent {
  export type InputTuple = [
    channel: BytesLike,
    admin: AddressLike,
    requiresPersonhood: boolean,
    minDim: BigNumberish
  ];
  export type OutputTuple = [
    channel: string,
    admin: string,
    requiresPersonhood: boolean,
    minDim: bigint
  ];
  export interface OutputObject {
    channel: string;
    admin: string;
    requiresPersonhood: boolean;
    minDim: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageBurnedEvent {
  export type InputTuple = [
    conversationId: BytesLike,
    index: BigNumberish,
    by: AddressLike
  ];
  export type OutputTuple = [conversationId: string, index: bigint, by: string];
  export interface OutputObject {
    conversationId: string;
    index: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    conversationId: BytesLike,
    from: AddressLike,
    to: AddressLike,
    channel: BytesLike,
    cid: string,
    expiresAt: BigNumberish,
    index: BigNumberish
  ];
  export type OutputTuple = [
    conversationId: string,
    from: string,
    to: string,
    channel: string,
    cid: string,
    expiresAt: bigint,
    index: bigint
  ];
  export interface OutputObject {
    conversationId: string;
    from: string;
    to: string;
    channel: string;
    cid: string;
    expiresAt: bigint;
    index: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Messenger extends BaseContract {
  connect(runner?: ContractRunner | null): Messenger;
  waitForDeployment(): Promise<this>;

  interface: MessengerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  burn: TypedContractMethod<
    [conversationId: BytesLike, index: BigNumberish],
    [void],
    "nonpayable"
  >;

  channels: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint, string, boolean] & {
        admin: string;
        requiresPersonhood: boolean;
        minDim: bigint;
        metadataCid: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  createChannel: TypedContractMethod<
    [
      channel: BytesLike,
      requiresPersonhood: boolean,
      minDim: BigNumberish,
      metadataCid: string
    ],
    [void],
    "nonpayable"
  >;

  dmId: TypedContractMethod<[a: AddressLike, b: AddressLike], [string], "view">;

  getMessages: TypedContractMethod<
    [conversationId: BytesLike, offset: BigNumberish, limit: BigNumberish],
    [Messenger.MessageStructOutput[]],
    "view"
  >;

  identity: TypedContractMethod<[], [string], "view">;

  individuality: TypedContractMethod<[], [string], "view">;

  messageCount: TypedContractMethod<
    [conversationId: BytesLike],
    [bigint],
    "view"
  >;

  sendDirect: TypedContractMethod<
    [to: AddressLike, cid: string, ttlSeconds: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  sendToChannel: TypedContractMethod<
    [channel: BytesLike, cid: string, ttlSeconds: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [conversationId: BytesLike, index: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "channels"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, boolean, bigint, string, boolean] & {
        admin: string;
        requiresPersonhood: boolean;
        minDim: bigint;
        metadataCid: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createChannel"
  ): TypedContractMethod<
    [
      channel: BytesLike,
      requiresPersonhood: boolean,
      minDim: BigNumberish,
      metadataCid: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dmId"
  ): TypedContractMethod<[a: AddressLike, b: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMessages"
  ): TypedContractMethod<
    [conversationId: BytesLike, offset: BigNumberish, limit: BigNumberish],
    [Messenger.MessageStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "individuality"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageCount"
  ): TypedContractMethod<[conversationId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sendDirect"
  ): TypedContractMethod<
    [to: AddressLike, cid: string, ttlSeconds: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendToChannel"
  ): TypedContractMethod<
    [channel: BytesLike, cid: string, ttlSeconds: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ChannelCreated"
  ): TypedContractEvent<
    ChannelCreatedEvent.InputTuple,
    ChannelCreatedEvent.OutputTuple,
    ChannelCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MessageBurned"
  ): TypedContractEvent<
    MessageBurnedEvent.InputTuple,
    MessageBurnedEvent.OutputTuple,
    MessageBurnedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;

  filters: {
    "ChannelCreated(bytes32,address,bool,uint8)": TypedContractEvent<
      ChannelCreatedEvent.InputTuple,
      ChannelCreatedEvent.OutputTuple,
      ChannelCreatedEvent.OutputObject
    >;
    ChannelCreated: TypedContractEvent<
      ChannelCreatedEvent.InputTuple,
      ChannelCreatedEvent.OutputTuple,
      ChannelCreatedEvent.OutputObject
    >;

    "MessageBurned(bytes32,uint256,address)": TypedContractEvent<
      MessageBurnedEvent.InputTuple,
      MessageBurnedEvent.OutputTuple,
      MessageBurnedEvent.OutputObject
    >;
    MessageBurned: TypedContractEvent<
      MessageBurnedEvent.InputTuple,
      MessageBurnedEvent.OutputTuple,
      MessageBurnedEvent.OutputObject
    >;

    "MessageSent(bytes32,address,address,bytes32,string,uint64,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
  };
}
