/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PaymentsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "identity"
      | "received"
      | "sent"
      | "tip"
      | "tipCount"
      | "tips"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TipSent"): EventFragment;

  encodeFunctionData(functionFragment: "identity", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "received",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "sent", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "tip",
    values: [AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "tipCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "tips", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "received", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tipCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tips", data: BytesLike): Result;
}

export namespace TipSentEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    conversationId: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    from: string,
    to: string,
    amount: bigint,
    conversationId: string
  ];
  export interface OutputObject {
    id: bigint;
    from: string;
    to: string;
    amount: bigint;
    conversationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Payments extends BaseContract {
  connect(runner?: ContractRunner | null): Payments;
  waitForDeployment(): Promise<this>;

  interface: PaymentsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  identity: TypedContractMethod<[], [string], "view">;

  received: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  sent: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  tip: TypedContractMethod<
    [to: AddressLike, conversationId: BytesLike, noteCid: string],
    [void],
    "payable"
  >;

  tipCount: TypedContractMethod<[], [bigint], "view">;

  tips: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint] & {
        from: string;
        to: string;
        amount: bigint;
        conversationId: string;
        noteCid: string;
        sentAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "received"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tip"
  ): TypedContractMethod<
    [to: AddressLike, conversationId: BytesLike, noteCid: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "tipCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tips"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint] & {
        from: string;
        to: string;
        amount: bigint;
        conversationId: string;
        noteCid: string;
        sentAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TipSent"
  ): TypedContractEvent<
    TipSentEvent.InputTuple,
    TipSentEvent.OutputTuple,
    TipSentEvent.OutputObject
  >;

  filters: {
    "TipSent(uint256,address,address,uint256,bytes32)": TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;
    TipSent: TypedContractEvent<
      TipSentEvent.InputTuple,
      TipSentEvent.OutputTuple,
      TipSentEvent.OutputObject
    >;
  };
}
