/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IIdentityRegistry {
  export type ProfileStruct = {
    encryptionPubKey: BytesLike;
    profileCid: string;
    personhood: boolean;
    registeredAt: BigNumberish;
  };

  export type ProfileStructOutput = [
    encryptionPubKey: string,
    profileCid: string,
    personhood: boolean,
    registeredAt: bigint
  ] & {
    encryptionPubKey: string;
    profileCid: string;
    personhood: boolean;
    registeredAt: bigint;
  };
}

export interface IIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "encryptionKeyOf" | "isRegistered" | "profileOf"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "encryptionKeyOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profileOf",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "encryptionKeyOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profileOf", data: BytesLike): Result;
}

export interface IIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encryptionKeyOf: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  isRegistered: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  profileOf: TypedContractMethod<
    [account: AddressLike],
    [IIdentityRegistry.ProfileStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encryptionKeyOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "profileOf"
  ): TypedContractMethod<
    [account: AddressLike],
    [IIdentityRegistry.ProfileStructOutput],
    "view"
  >;

  filters: {};
}
